import type { HealthReport, Units } from "../health/models";

const escapeHtml = (value: string) => value.replace(/[&<>'"]/g, (character) => ({ "&": "&amp;", "<": "&lt;", ">": "&gt;", "'": "&#39;", '"': "&quot;" })[character]!);
const fmt = (value: number, digits = 0) => new Intl.NumberFormat("en", { maximumFractionDigits: digits }).format(value);
const duration = (minutes: number | null) => minutes === null ? "No data" : `${Math.floor(Math.round(minutes) / 60)}h ${Math.round(minutes) % 60}m`;

export function exportReport(report: HealthReport, units: Units): void {
  const distance = (meters: number) => units === "metric" ? `${fmt(meters / 1000, 1)} km` : `${fmt(meters / 1609.344, 1)} mi`;
  const weight = report.summary.latestWeightGrams === null ? "No data" : units === "metric" ? `${fmt(report.summary.latestWeightGrams / 1000, 1)} kg` : `${fmt(report.summary.latestWeightGrams / 453.59237, 1)} lb`;
  const data = JSON.stringify({ activity: report.activity, heartRate: report.heartRate }).replace(/</g, "\\u003c");
  const activityRows = [...report.activity].reverse().map((day) => `<tr><td>${escapeHtml(day.date)}</td><td>${fmt(day.steps)}</td><td>${distance(day.distanceMeters)}</td><td>${fmt(day.energyJoules / 4184)} kcal</td></tr>`).join("");
  const exerciseRows = report.exercises.map((session) => `<tr><td>${escapeHtml(new Date(session.start).toLocaleString())}</td><td>${escapeHtml(session.title || session.typeName)}</td><td>${duration(session.durationMinutes)}</td><td>${session.average === null ? "—" : `${fmt(session.average)} bpm`}</td><td>${fmt(session.estimatedSteps)} est.</td><td>${escapeHtml(session.source)}</td></tr>`).join("");
  const sleepRows = report.sleep.map((session) => {
    const stages = session.stageTotals.map((stage) => `${escapeHtml(stage.name)} ${duration(stage.minutes)} (${fmt(stage.percentage, 1)}%)`).join(" · ");
    const latency = session.detailed.sleepLatencyMinutes === null ? "—" : duration(session.detailed.sleepLatencyMinutes);
    const waso = session.detailed.wakeAfterSleepOnsetMinutes === null ? "—" : duration(session.detailed.wakeAfterSleepOnsetMinutes);
    return `<tr><td>${escapeHtml(new Date(session.end).toLocaleDateString())}</td><td>${duration(session.asleepMinutes)}</td><td>${fmt(session.efficiency, 1)}%</td><td>${session.awakenings}</td><td>${latency}</td><td>${waso}</td><td>${stages}</td></tr>`;
  }).join("");
  const warnings = report.warnings.map((warning) => `<li>${escapeHtml(warning)}</li>`).join("");
  const sources = report.sources.map((source) => `<li><span><b>${escapeHtml(source.name)}</b><small>${escapeHtml(source.packageName)}</small></span><strong>${fmt(source.records)} records</strong></li>`).join("");

  const html = `<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Health report · ${escapeHtml(report.range.selectedFrom)}</title><style>
  :root{--bg:#f4f7f9;--paper:#fff;--ink:#17232d;--muted:#647381;--line:#dce5ea;--teal:#168477;--blue:#3979be;--coral:#c75b59;--amber:#c57a2c;color-scheme:light}*{box-sizing:border-box}body{margin:0;background:var(--bg);color:var(--ink);font-family:Arial,sans-serif}.wrap{max-width:1220px;margin:auto;padding:48px 26px 90px}header{display:flex;justify-content:space-between;gap:30px;align-items:start;border-bottom:1px solid var(--line);padding-bottom:25px}h1{font:600 clamp(48px,8vw,86px) Georgia,serif;letter-spacing:-.055em;line-height:.9;margin:12px 0}.kicker,label{font:700 10px monospace;text-transform:uppercase;letter-spacing:.12em;color:var(--teal)}header p{max-width:430px;color:var(--muted);line-height:1.6}.controls{display:flex;gap:8px}button{padding:9px 12px;border:1px solid var(--line);background:var(--paper);color:var(--ink)}.summary{display:grid;grid-template-columns:repeat(6,1fr);gap:10px;margin:25px 0}.card{min-height:120px;padding:16px;display:flex;flex-direction:column;border:1px solid var(--line);border-top:4px solid var(--teal);border-radius:12px;background:var(--paper)}.card:nth-child(4){border-top-color:var(--coral)}.card:nth-child(5){border-top-color:#7957a5}.card b{margin:auto 0 4px;font:600 24px Georgia}.card small{color:var(--muted)}section{margin-top:14px;padding:22px;border:1px solid var(--line);border-radius:14px;background:var(--paper)}section h2{margin:4px 0 20px;font:600 24px Georgia}.chart{height:280px}.grid{display:grid;grid-template-columns:1.3fr .7fr;gap:14px}.table{overflow:auto}table{width:100%;border-collapse:collapse;font-size:12px}th,td{padding:11px;border-bottom:1px solid var(--line);text-align:left;vertical-align:top}th{color:var(--muted);font:700 9px monospace;text-transform:uppercase}.sources{list-style:none;padding:0}.sources li{padding:12px 0;display:flex;justify-content:space-between;border-bottom:1px solid var(--line)}.sources span{display:flex;flex-direction:column}.sources small{color:var(--muted)}.notes li{margin:8px 0;color:#765322;line-height:1.5}.meta{margin-top:28px;color:var(--muted);font:11px monospace}.empty{height:150px;display:grid;place-items:center;color:var(--muted)}
  .dark{--bg:#101614;--paper:#18201d;--ink:#e9efec;--muted:#a8b5af;--line:#34423c;--teal:#79d5c4;--blue:#83b4e8;--coral:#e88d88;--amber:#e2a55d;color-scheme:dark}@media(max-width:800px){header{flex-direction:column}.summary{grid-template-columns:1fr 1fr}.grid{grid-template-columns:1fr}.wrap{padding:26px 12px 60px}}@media print{.controls{display:none}.wrap{padding:8px}section,.card{break-inside:avoid}}
  </style></head><body><main class="wrap"><header><div><span class="kicker">Private health field report</span><h1>Your health,<br>in context.</h1></div><div><div class="controls"><button onclick="window.print()">Print report</button><button onclick="document.documentElement.classList.toggle('dark')">Toggle theme</button></div><p>${escapeHtml(report.range.selectedFrom)} through ${escapeHtml(report.range.selectedTo)}. Generated locally from ${escapeHtml(report.fileName)} on ${escapeHtml(new Date(report.generatedAt).toLocaleString())}.</p></div></header>
  <div class="summary"><article class="card"><label>Steps</label><b>${fmt(report.summary.totalSteps)}</b><small>${fmt(report.summary.averageDailySteps)} daily</small></article><article class="card"><label>Distance</label><b>${distance(report.summary.totalDistanceMeters)}</b><small>recorded</small></article><article class="card"><label>Exercise</label><b>${duration(report.summary.exerciseMinutes)}</b><small>${report.summary.exerciseCount} sessions</small></article><article class="card"><label>Heart rate</label><b>${report.summary.heartRateAverage === null ? "No data" : `${fmt(report.summary.heartRateAverage)} bpm`}</b><small>${report.summary.heartRateMin === null ? "No samples" : `${fmt(report.summary.heartRateMin)}–${fmt(report.summary.heartRateMax!)} bpm`}</small></article><article class="card"><label>Sleep</label><b>${duration(report.summary.averageAsleepMinutes)}</b><small>${report.summary.averageSleepEfficiency === null ? "No data" : `${fmt(report.summary.averageSleepEfficiency, 1)}% efficient`}</small></article><article class="card"><label>Latest weight</label><b>${weight}</b><small>${report.weight.length} measurements</small></article></div>
  <section><label>Activity</label><h2>Steps across the selected period</h2>${report.activity.length ? '<div class="chart"><canvas id="activity"></canvas></div>' : '<div class="empty">No activity records</div>'}</section>
  <section><label>Heart</label><h2>Five-minute heart-rate averages</h2>${report.heartRate.length ? '<div class="chart"><canvas id="heart"></canvas></div>' : '<div class="empty">No heart-rate samples</div>'}</section>
  <section><label>Sleep</label><h2>Recorded sleep-stage summaries</h2><div class="table"><table><thead><tr><th>Night</th><th>Asleep</th><th>Efficiency</th><th>Awakenings</th><th>Latency</th><th>Awake after onset</th><th>Recorded stages</th></tr></thead><tbody>${sleepRows || '<tr><td colspan="7">No sleep sessions</td></tr>'}</tbody></table></div></section>
  <section><label>Exercise</label><h2>Workout sessions</h2><div class="table"><table><thead><tr><th>Started</th><th>Activity</th><th>Duration</th><th>Average HR</th><th>Steps</th><th>Source</th></tr></thead><tbody>${exerciseRows || '<tr><td colspan="6">No sessions</td></tr>'}</tbody></table></div></section>
  <div class="grid"><section><label>Daily detail</label><h2>Movement ledger</h2><div class="table"><table><thead><tr><th>Date</th><th>Steps</th><th>Distance</th><th>Energy</th></tr></thead><tbody>${activityRows || '<tr><td colspan="4">No records</td></tr>'}</tbody></table></div></section><section><label>Provenance</label><h2>Contributing apps</h2><ul class="sources">${sources || "<li>No source details</li>"}</ul></section></div>
  <section class="notes"><label>Read with care</label><h2>Data quality notes</h2><ul>${warnings || "<li>No quality warnings for this selection.</li>"}</ul></section><p class="meta">Schema ${report.schemaVersion} · ${report.availableTables.length} tables detected · Generated entirely in your browser. Workout overlap values are estimated. This report is informational and not medical advice.</p></main>
  <script>const DATA=${data};function draw(id,points,key,color){const c=document.getElementById(id);if(!c||!points.length)return;const d=devicePixelRatio||1,r=c.getBoundingClientRect();c.width=r.width*d;c.height=r.height*d;const x=c.getContext('2d');x.scale(d,d);const w=r.width,h=r.height,p=28,vals=points.map(q=>q[key]),max=Math.max(...vals),min=Math.min(...vals,0),range=max-min||1;x.clearRect(0,0,w,h);x.strokeStyle=getComputedStyle(document.documentElement).getPropertyValue('--line');for(let i=0;i<4;i++){const y=p+(h-2*p)*i/3;x.beginPath();x.moveTo(p,y);x.lineTo(w-p,y);x.stroke()}x.strokeStyle=color;x.fillStyle=color;x.lineWidth=2;x.beginPath();points.forEach((q,i)=>{const px=p+(w-2*p)*(i/Math.max(1,points.length-1)),py=h-p-(h-2*p)*((q[key]-min)/range);if(id==='activity'){const bw=Math.max(2,(w-2*p)/points.length*.65);x.fillRect(px-bw/2,py,bw,h-p-py)}else{i?x.lineTo(px,py):x.moveTo(px,py)}});if(id!=='activity')x.stroke()}function render(){draw('activity',DATA.activity,'steps','#168477');draw('heart',DATA.heartRate,'value','#c75b59')}render();addEventListener('resize',render);</script></body></html>`;

  const blob = new Blob([html], { type: "text/html;charset=utf-8" });
  const url = URL.createObjectURL(blob);
  const link = document.createElement("a");
  link.href = url;
  link.download = `health-report-${report.range.selectedFrom}-to-${report.range.selectedTo}.html`;
  link.click();
  setTimeout(() => URL.revokeObjectURL(url), 1000);
}
