import type { HealthReport, Units } from "../health/models";

const escapeHtml = (value: string) => value.replace(/[&<>'"]/g, (character) => ({ "&": "&amp;", "<": "&lt;", ">": "&gt;", "'": "&#39;", '"': "&quot;" })[character]!);
const fmt = (value: number, digits = 0) => new Intl.NumberFormat("en", { maximumFractionDigits: digits }).format(value);

export function exportReport(report: HealthReport, units: Units): void {
  const distance = units === "metric" ? `${fmt(report.summary.totalDistanceMeters / 1000, 1)} km` : `${fmt(report.summary.totalDistanceMeters / 1609.344, 1)} mi`;
  const weight = report.summary.latestWeightGrams === null ? "No data" : units === "metric" ? `${fmt(report.summary.latestWeightGrams / 1000, 1)} kg` : `${fmt(report.summary.latestWeightGrams / 453.59237, 1)} lb`;
  const data = JSON.stringify({ activity: report.activity, heartRate: report.heartRate }).replace(/</g, "\\u003c");
  const activityRows = [...report.activity].reverse().map((day) => `<tr><td>${escapeHtml(day.date)}</td><td>${fmt(day.steps)}</td><td>${fmt(units === "metric" ? day.distanceMeters / 1000 : day.distanceMeters / 1609.344, 2)} ${units === "metric" ? "km" : "mi"}</td><td>${fmt(day.energyJoules / 4184, 0)} kcal</td></tr>`).join("");
  const exerciseRows = report.exercises.map((session) => `<tr><td>${escapeHtml(new Date(session.start).toLocaleString())}</td><td>${escapeHtml(session.title || session.typeName)}</td><td>${fmt(session.durationMinutes)} min</td><td>${escapeHtml(session.source)}</td></tr>`).join("");
  const warnings = report.warnings.map((warning) => `<li>${escapeHtml(warning)}</li>`).join("");
  const sources = report.sources.map((source) => `<li><span><b>${escapeHtml(source.name)}</b><small>${escapeHtml(source.packageName)}</small></span><strong>${fmt(source.records)} records</strong></li>`).join("");

  const html = `<!doctype html>
<html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><link rel="icon" href="data:,"><title>Health report · ${escapeHtml(report.range.selectedFrom)}</title>
<style>
:root{--bg:#e9efeb;--paper:#f8faf8;--ink:#26322d;--muted:#6a7771;--sage:#537b69;--coral:#b94f47;--line:#d2ddd6;color-scheme:light}*{box-sizing:border-box}body{margin:0;background:var(--bg);color:var(--ink);font-family:Arial,sans-serif}.wrap{max-width:1180px;margin:auto;padding:50px 28px 90px}header{display:flex;justify-content:space-between;gap:30px;align-items:start;border-bottom:1px solid var(--line);padding-bottom:28px}header h1{font:500 clamp(48px,8vw,90px) Georgia,serif;letter-spacing:-.05em;line-height:.9;margin:14px 0}.kicker,label{font:700 10px monospace;text-transform:uppercase;letter-spacing:.13em;color:var(--sage)}header p{color:var(--muted);max-width:380px;line-height:1.6}.controls{display:flex;gap:8px}button{border:1px solid var(--line);background:var(--paper);padding:9px 12px;color:var(--ink);cursor:pointer}.summary{display:grid;grid-template-columns:repeat(5,1fr);gap:10px;margin:26px 0}.card{background:var(--paper);border-top:3px solid var(--sage);padding:18px;min-height:130px;display:flex;flex-direction:column}.card:nth-child(4){border-color:var(--coral)}.card b{font:500 29px Georgia;margin:auto 0 5px}.card small{color:var(--muted)}section{background:var(--paper);padding:24px;margin-top:16px}section h2{font:500 25px Georgia;margin:4px 0 22px}.chart{height:300px;position:relative}canvas{width:100%;height:100%}.grid{display:grid;grid-template-columns:1.4fr .6fr;gap:16px}.table{overflow:auto}table{width:100%;border-collapse:collapse;font-size:12px}th,td{padding:12px;border-bottom:1px solid var(--line);text-align:left}th{font:700 9px monospace;text-transform:uppercase;color:var(--muted)}.notes li{margin:10px 0;color:#705c3d;line-height:1.5}.sources{list-style:none;padding:0}.sources li{display:flex;justify-content:space-between;border-bottom:1px solid var(--line);padding:13px 0}.sources span{display:flex;flex-direction:column}.sources small{color:var(--muted);margin-top:3px}.meta{font:11px monospace;color:var(--muted);margin-top:28px}.empty{height:200px;display:grid;place-items:center;color:var(--muted);border:1px dashed var(--line)}
@media(max-width:800px){header{flex-direction:column}.summary{grid-template-columns:1fr 1fr}.grid{grid-template-columns:1fr}.wrap{padding:28px 14px 60px}}@media(prefers-color-scheme:dark){:root{--bg:#17231f;--paper:#22312b;--ink:#e8eeea;--muted:#9dadA5;--line:#3d4e46;--sage:#8cb59f;--coral:#df8176;color-scheme:dark}}.forced-dark{--bg:#17231f;--paper:#22312b;--ink:#e8eeea;--muted:#9dada5;--line:#3d4e46;--sage:#8cb59f;--coral:#df8176;color-scheme:dark}@media print{.controls{display:none}.wrap{padding:10px}section,.card{break-inside:avoid}}
</style></head><body><main class="wrap"><header><div><span class="kicker">Health Connect field report</span><h1>Your health,<br>in context.</h1></div><div><div class="controls"><button onclick="window.print()">Print report</button><button onclick="document.documentElement.classList.toggle('forced-dark')">Toggle contrast</button></div><p>${escapeHtml(report.range.selectedFrom)} through ${escapeHtml(report.range.selectedTo)}. Generated locally from ${escapeHtml(report.fileName)} on ${escapeHtml(new Date(report.generatedAt).toLocaleString())}.</p></div></header>
<div class="summary"><article class="card"><label>Total steps</label><b>${fmt(report.summary.totalSteps)}</b><small>${fmt(report.summary.averageDailySteps)} daily average</small></article><article class="card"><label>Distance</label><b>${distance}</b><small>recorded movement</small></article><article class="card"><label>Energy</label><b>${fmt(report.summary.totalEnergyJoules/4184)} kcal</b><small>total recorded</small></article><article class="card"><label>Heart rate</label><b>${report.summary.heartRateAverage === null ? "No data" : `${fmt(report.summary.heartRateAverage)} bpm`}</b><small>${report.summary.heartRateMin === null ? "No samples" : `${fmt(report.summary.heartRateMin)}–${fmt(report.summary.heartRateMax!)} bpm`}</small></article><article class="card"><label>Latest weight</label><b>${weight}</b><small>${report.weight.length} measurements</small></article></div>
<section><label>Activity trace</label><h2>Steps across the selected period</h2>${report.activity.length ? '<div class="chart"><canvas id="activity"></canvas></div>' : '<div class="empty">No activity records</div>'}</section>
<section><label>Cardiovascular signal</label><h2>Five-minute heart-rate averages</h2>${report.heartRate.length ? '<div class="chart"><canvas id="heart"></canvas></div>' : '<div class="empty">No heart-rate samples</div>'}</section>
<div class="grid"><section><label>Daily detail</label><h2>Movement ledger</h2><div class="table"><table><thead><tr><th>Date</th><th>Steps</th><th>Distance</th><th>Energy</th></tr></thead><tbody>${activityRows || '<tr><td colspan="4">No records</td></tr>'}</tbody></table></div></section><section><label>Provenance</label><h2>Contributing apps</h2><ul class="sources">${sources || "<li>No source details</li>"}</ul></section></div>
<section><label>Exercise</label><h2>Session log</h2><div class="table"><table><thead><tr><th>Started</th><th>Activity</th><th>Duration</th><th>Source</th></tr></thead><tbody>${exerciseRows || '<tr><td colspan="4">No sessions</td></tr>'}</tbody></table></div></section>
<section class="notes"><label>Read with care</label><h2>Data quality notes</h2><ul>${warnings || "<li>No quality warnings for this selection.</li>"}</ul></section><p class="meta">Schema ${report.schemaVersion} · ${report.availableTables.length} tables detected · Generated entirely in your browser. This report is informational and not medical advice.</p></main>
<script>const DATA=${data};function draw(id,points,key,color){const c=document.getElementById(id);if(!c||!points.length)return;const d=devicePixelRatio||1,r=c.getBoundingClientRect();c.width=r.width*d;c.height=r.height*d;const x=c.getContext('2d');x.scale(d,d);const w=r.width,h=r.height,p=28,vals=points.map(q=>q[key]),max=Math.max(...vals),min=Math.min(...vals,0),range=max-min||1;x.strokeStyle=getComputedStyle(document.documentElement).getPropertyValue('--line');x.lineWidth=1;for(let i=0;i<4;i++){const y=p+(h-2*p)*i/3;x.beginPath();x.moveTo(p,y);x.lineTo(w-p,y);x.stroke()}x.strokeStyle=color;x.fillStyle=color;x.lineWidth=2;x.beginPath();points.forEach((q,i)=>{const px=p+(w-2*p)*(i/Math.max(1,points.length-1)),py=h-p-(h-2*p)*((q[key]-min)/range);if(id==='activity'){const bw=Math.max(2,(w-2*p)/points.length*.65);x.fillRect(px-bw/2,py,bw,h-p-py)}else{i?x.lineTo(px,py):x.moveTo(px,py)}});if(id!=='activity')x.stroke()}draw('activity',DATA.activity,'steps','#668f7b');draw('heart',DATA.heartRate,'value','#c7655b');addEventListener('resize',()=>{draw('activity',DATA.activity,'steps','#668f7b');draw('heart',DATA.heartRate,'value','#c7655b')});</script></body></html>`;

  const blob = new Blob([html], { type: "text/html;charset=utf-8" });
  const url = URL.createObjectURL(blob);
  const link = document.createElement("a");
  link.href = url;
  link.download = `health-report-${report.range.selectedFrom}-to-${report.range.selectedTo}.html`;
  link.click();
  setTimeout(() => URL.revokeObjectURL(url), 1000);
}
